version: "3"
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 5556:80
    volumes:
      - ./:/srv/app
      - /srv/app/vendor
  php_dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8887:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: phpmyadminB00768327
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8886:80
    volumes:
      - /sessions
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_php
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker_php
      MYSQL_PASSWORD: secret
volumes:
  db:
    driver: local